#! /usr/bin/env bash

help() {
  # This prints a help page which provides a list of options.
  HELP_MESSAGE='This is a place holder for the real help message.'
  printf "%s" "${HELP_MESSAGE}"
}

placepiece() {
    printf "" >> "${1}"
}

hideaway() {
  while true
    do
      printf "\033c"
      printf "=======================================================================\n"
      printf "Choose your hiding places----\n" #TODO: That sounds so lame! I have to change that.
      printf "======================================================================="
      #TODO: What are we calling these "things" we're putting in the directories?
      #TODO: Discuss which directories we wish to use.
      printf "Enter 1 to place in /home/pupi/Desktop \n"
      printf "Enter 2 to place [??] in [??]: \n"
      printf "Enter 3 to place [??] in [??]: \n"
      #TODO: add more options. Choose x out of total y? 
       "Enter r to exit menu r: "
      printf "\n"
      read -p "Enter your selection \c"
      case "$answer" in
        1) placepiece  ;;  #TODO: dirpath=/path/to/piece"; placepiece $dirpath 
        2)  ;;
        3)  ;;
        r) exit;; #TODO: Really needs to be return to main menu. Right?
      esac
      printf "\n"
      read -p "Enter return to continue \c"
    done
}

main() {
  while getopts "h" OPTION; do
    case "${OPTION}" in
      h)
        help
        exit 1;;
      s) 
        hideaway()
        exit 1;;
    esac
  done
}

main "${@}"
